# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezjxh5i8Upf8hEf6vnN5AqbYNxe6blz8
"""

# =========================================================
# IMPORT LIBRARY
# =========================================================

import pandas as pd

from flask import Flask, render_template_string

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, r2_score

# =========================================================
# DATASET CAFE
# =========================================================

data = {

    "Tanggal": [
        "2026-05-01",
        "2026-05-02",
        "2026-05-03",
        "2026-05-04",
        "2026-05-05",
        "2026-05-06",
        "2026-05-07",
        "2026-05-08",
        "2026-05-09",
        "2026-05-10"
    ],

    "Cuaca": [
        "Cerah",
        "Hujan",
        "Mendung",
        "Cerah",
        "Hujan",
        "Cerah",
        "Mendung",
        "Cerah",
        "Hujan",
        "Cerah"
    ],

    "Hari_Libur": [
        0,1,1,0,0,
        0,0,1,1,0
    ],

    "Promo": [
        1,1,0,0,1,
        1,0,1,1,0
    ],

    "Jam_Operasional": [
        12,14,10,11,9,
        13,10,15,14,11
    ],

    "Pengunjung": [
        220,260,150,180,110,
        240,170,310,280,190
    ]
}

df = pd.DataFrame(data)

# =========================================================
# ANALISIS BERDASARKAN CUACA
# =========================================================

analisis_cuaca = df.groupby("Cuaca")["Pengunjung"].agg([
    "sum",
    "mean",
    "max",
    "min"
])

# =========================================================
# LABEL ENCODING
# =========================================================

le = LabelEncoder()

df["Cuaca"] = le.fit_transform(df["Cuaca"])

# =========================================================
# FITUR DAN TARGET
# =========================================================

X = df[[
    "Cuaca",
    "Hari_Libur",
    "Promo",
    "Jam_Operasional"
]]

y = df["Pengunjung"]

# =========================================================
# SPLIT DATA
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================================================
# MODEL REGRESI LINEAR
# =========================================================

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

linear_pred = linear_model.predict(X_test)

# =========================================================
# MODEL RANDOM FOREST
# =========================================================

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

# =========================================================
# EVALUASI MODEL
# =========================================================

mae = mean_absolute_error(y_test, linear_pred)

r2 = r2_score(y_test, linear_pred)

# =========================================================
# PREDIKSI DATA BARU
# =========================================================

data_baru = pd.DataFrame({

    "Cuaca": [0],

    "Hari_Libur": [1],

    "Promo": [1],

    "Jam_Operasional": [14]

})

pred_linear = round(
    linear_model.predict(data_baru)[0]
)

pred_rf = round(
    rf_model.predict(data_baru)[0]
)

# =========================================================
# FLASK APP
# =========================================================

app = Flask(__name__)

# =========================================================
# HALAMAN WEB
# =========================================================

@app.route("/")

def home():

    return render_template_string("""

    <html>

    <head>

        <title>Prediksi Pengunjung Cafe</title>

        <style>

            body{
                font-family:Arial;
                background:#f5f5f5;
                padding:40px;
            }

            .container{
                max-width:1000px;
                margin:auto;
            }

            .card{
                background:white;
                padding:20px;
                border-radius:15px;
                margin-bottom:20px;
                box-shadow:0 0 10px rgba(0,0,0,0.1);
            }

            table{
                width:100%;
                border-collapse:collapse;
            }

            table, th, td{
                border:1px solid #ccc;
            }

            th, td{
                padding:10px;
                text-align:center;
            }

            h1{
                color:#333;
            }

        </style>

    </head>

    <body>

        <div class="container">

            <div class="card">

                <h1>
                    Prediksi Jumlah Pengunjung Cafe
                </h1>

                <p>
                    Berdasarkan Cuaca, Hari Libur,
                    Promo, dan Jam Operasional
                </p>

            </div>

            <div class="card">

                <h2>Dataset Cafe</h2>

                {{ data|safe }}

            </div>

            <div class="card">

                <h2>Analisis Berdasarkan Cuaca</h2>

                {{ cuaca|safe }}

            </div>

            <div class="card">

                <h2>Evaluasi Model</h2>

                <p>MAE : {{ mae }}</p>

                <p>R2 : {{ r2 }}</p>

            </div>

            <div class="card">

                <h2>Hasil Prediksi</h2>

                <p>
                    Prediksi Regresi Linear :
                    <b>{{ pred_linear }}</b>
                </p>

                <p>
                    Prediksi Random Forest :
                    <b>{{ pred_rf }}</b>
                </p>

            </div>

        </div>

    </body>

    </html>

    """,

    data=df.to_html(index=False),

    cuaca=analisis_cuaca.to_html(),

    mae=round(mae,2),

    r2=round(r2,2),

    pred_linear=pred_linear,

    pred_rf=pred_rf
    )

# =========================================================
# MENJALANKAN WEB
# =========================================================

if __name__ == "__main__":

    app.run(debug=True)
